services:
  web:
    image: ghcr.io/goodjoon-company/goodmoneying-web:${GOODMONEYING_IMAGE_TAG}
    container_name: goodmoneying-web
    restart: unless-stopped
    env_file:
      - ${GOODMONEYING_WEB_BASE_DIR}/env/web.env
    volumes:
      - ${GOODMONEYING_WEB_NGINX_CACHE_DIR}:/var/cache/nginx
      - ${GOODMONEYING_WEB_CONFIG_DIR}:/etc/goodmoneying:ro
    ports:
      - "100.68.208.102:8080:80"
